### ISSUE TITLE
Allow creation of symlinks

### ISSUE THREAD

**Issue by JasonN3** [flightctl/flightctl#1228]
If you create a symlink in git and then reference the directory containing the symlink as a configuration for a fleet, the link will be followed and the content of the resulting file will be created on the device. It should be created on the device as a symlink. Otherwise, the content may be drastically different than you expect if you're trying to create a link to something locally on the machine.

If being able to follow symlinks is potentially desirable, it may be worth adding a `followSymlinks` options for gitRefs that allows someone to decide if they want symlinks created on the resulting device or have the file created with the content of the linked file.

Example of current situation:
```
git repo:
  file1: content of file1
  file2 -> file1

gitRef:
  mountPath: /
  path: /
  repository: example
  targetRevision: main

Result:
  file1: content of file1
  file2: content of file1
```

Desired result:
```
git repo:
  file1: content of file1
  file2 -> file1

gitRef:
  mountPath: /
  path: /
  repository: example
  targetRevision: main

Result:
  file1: content of file1
  file2 -> file1
```
