### ISSUE TITLE
Bootc image manager design

### ISSUE THREAD

**Issue by hexfusion** [flightctl/flightctl#180]
### Bootc image manager draft.

This issue describes the high level functionality required for the bootc image manager.  The image manager must be able to query for status from the bootc host and provide the following functionality.

#### bootstrap phase

- check: status.bootcHost if this is set true then all further interactions with the image Manager will use bootc commands. Today we only support bootc so anything else should fail bootstrap.

- First check `spec.image.image` = `status.booted.image.image.image` if yes then we have `reconciled` image on bootc level. 
- Next If `device.current.spec.Os` == `device.desired.spec.Os` is false then we are `progressing` . This means we are in a transition state and since we are seeing this during bootstrap we should have either recently upgraded or recently failed to upgrade.
- If `reconciled` and `progressing` os image has been reconciled. replace current spec with desired.
- If `reconciled` and not `progressing` happy path no image update `bootstrap complete`
- If `reconciled` false the image update failed [retry?] this requires more thought with regards to default behavior.

#### bootstrap phase flow diagram
```mermaid
graph TD;
    A[Start: Query `bootc status`] -->|status.bootcHost set| B[Use bootc commands];
    A -->|status.bootcHost not set| X[Bootstrap Failed];
    B --> C[Verify OS Image Sanity];
    C --> D{Check spec.image.image = status.booted.image.image.image};
    D -->|Yes| E[Reconciled: Upgrade Complete];
    D -->|No| I[Degraded=true,Progressing=true.Available=false Retry?];
    E --> F{Check device.current.spec.Os == device.desired.spec.Os};
    F -->|False| G[Degraded=false,Progressing=true.Available=true];
    F -->|True| J[Degraded=false,Progressing=false.Available=true];
    G --> H[Reconciled and Progressing: Replace current with desired];
    H --> L[Degraded=false,Progressing=false.Available=true];
    L --> K
    J --> K[Reconciled and Not Progressing: Bootstrap Complete];

```

**Comment by oglok** [comment]
There could be the case that `spec.image.image == status.booted.image.image.image` and still not `reconciled` because there is a newer version (upgrade) in staged mode. This state would miss a reboot to the to a reconciled state (if successful).

```
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: quay.io/flightctl/flightctl-agent-centos:bootstrap
    transport: registry
status:
  staged:
    image:
      image:
        image: quay.io/flightctl/flightctl-agent-centos:bootstrap
        transport: registry
      version: stream9.20240315.0
      timestamp: null
      imageDigest: sha256:7fa6cadba6f9c2cfbc8c6bc7040ce35868a7d9482206ca1f1bff8169567a4fa8
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: f97a76fa3893d58afc80ae804abdb2a936f09570c0902d43b16df7eb94e715e4
      deploySerial: 0
  booted:
    image:
      image:
        image: quay.io/flightctl/flightctl-agent-centos:bootstrap
        transport: registry
      version: stream9.20240314.0
      timestamp: null
      imageDigest: sha256:dc80b05838bbd295466c623a62cf60cd2e0f4dc0b3e364910e4c5f7f71a5e316
    cachedUpdate:
      image:
        image: quay.io/flightctl/flightctl-agent-centos:bootstrap
        transport: registry
      version: stream9.20240315.0
      timestamp: null
      imageDigest: sha256:7fa6cadba6f9c2cfbc8c6bc7040ce35868a7d9482206ca1f1bff8169567a4fa8
    incompatible: false
    pinned: false
    ostree:
      checksum: e5e6ab36954d50480a9d4d61bc57d036336f5384841d84d6ebe61057acbb3a6e
      deploySerial: 0
  rollback:
    image:
      image:
        image: quay.io/flightctl/flightctl-agent-centos:bootstrap
        transport: registry
      version: stream9.20240313.0
      timestamp: null
      imageDigest: sha256:08ba4400aa5534893774e8b0e887fd899cc440512dba816a11629804dac0f815
    cachedUpdate:
      image:
        image: quay.io/flightctl/flightctl-agent-centos:bootstrap
        transport: registry
      version: stream9.20240314.0
      timestamp: null
      imageDigest: sha256:dc80b05838bbd295466c623a62cf60cd2e0f4dc0b3e364910e4c5f7f71a5e316
    incompatible: false
    pinned: false
    ostree:
      checksum: bf9ebe855feec65f578f81a7229530a2c7c8381ce425c0acf7f650a1f5b618e2
      deploySerial: 0
  type: bootcHost
  ```
